### ISSUE TITLE
/nCoV/api/area接口返回的国外历史数据有误

### ISSUE THREAD

**Issue by Vege1994** [hack-fang/nCov#12]
这个接口返回的日本等地方的历史数据和世界卫生组织发布在[https://www.who.int/emergencies/diseases/novel-coronavirus-2019/situation-reports/]的日韩等国的数据对不上, 希望可以校正.附上的文件为手动收集的报告数据
[WHOCoVID19Data.xlsx](https://github.com/hack-fang/nCov/files/4254449/WHOCoVID19Data.xlsx)

**Comment by hack-fang** [comment]
> 
> 
> 这个接口返回的日本等地方的历史数据和世界卫生组织发布在[https://www.who.int/emergencies/diseases/novel-coronavirus-2019/situation-reports/]的日韩等国的数据对不上, 希望可以校正.附上的文件为手动收集的报告数据
> [WHOCoVID19Data.xlsx](https://github.com/hack-fang/nCov/files/4254449/WHOCoVID19Data.xlsx)

感谢您提供的数据来源，目前接口的数据来源为丁香园，与世卫组织提供的有所出入，目前不打算更改丁香园提供的数据。计划考虑根据世卫组织的数据，提供另一接口实现数据更新，以后每日手动更新数据，目前需要一些时间完成录入工作。

**Comment by Vege1994** [comment]
辛苦啦!
