### ISSUE TITLE
增加广东省不成功

### ISSUE THREAD

**Issue by quuhua911** [hack-fang/nCov#2]
我按照你的说明修改了 templates/index.html和 static/js/update.js 文件 增加了广东省,但是无法显示,看日志似乎广东的数据没有获取成功,能否指导一下是什么原因?

**Comment by hack-fang** [comment]
1. 代码是否是最新的版本呢？如果不是，请使用最新的版本。
2. 如果是最新的版本，请确认是否是地图包未导入。刚才我试了添加广东是可以的。
![图片](https://user-images.githubusercontent.com/12555752/73431928-871c3580-437c-11ea-80ac-04f9bd67c049.png)

**Comment by hack-fang** [comment]
> 
> 
> 我按照你的说明修改了 templates/index.html和 static/js/update.js 文件 增加了广东省,但是无法显示,看日志似乎广东的数据没有获取成功,能否指导一下是什么原因?

如上所言

**Comment by quuhua911** [comment]
代码是最新的.地图包也导入了.
        
        update_china("china");
        update_province("浙江省","zhejiang");
        update_province("广东省","guangdong");

    <script type="text/javascript" src="/static/vendor/map/zhejiang.js"></script>
    <script type="text/javascript" src="/static/vendor/map/guangdong.js"></script>


看了下日志,就是广东的数据没有取过来,不知道为啥?
127.0.0.1 - - [30/Jan/2020 19:05:05] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:07] "GET /poverall/安徽省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:07] "GET /rank HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:07] "GET /news HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:08] "GET /overall HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:08] "GET /pnews/安徽省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:09] "GET /map HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:09] "GET /pmap/安徽省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:09] "GET /prank/安徽省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:09] "GET /poverall/河北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:09] "GET /pnews/河北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:09] "GET /pmap/河北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:10] "GET /prank/河北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:20] "GET /poverall/湖北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:20] "GET /pnews/湖北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:20] "GET /pmap/湖北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:20] "GET /poverall/浙江省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:20] "GET /pnews/浙江省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:21] "GET /prank/湖北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:23] "GET /pmap/浙江省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:23] "GET /prank/浙江省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:24] "GET /poverall/安徽省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:25] "GET /rank HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:25] "GET /news HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:25] "GET /overall HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:25] "GET /pnews/安徽省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:26] "GET /pmap/安徽省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:26] "GET /map HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:26] "GET /prank/安徽省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:26] "GET /poverall/河北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:27] "GET /pnews/河北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:28] "GET /pmap/河北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:28] "GET /prank/河北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:28] "GET /poverall/湖北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:28] "GET /pnews/湖北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:28] "GET /pmap/湖北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:28] "GET /poverall/浙江省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:28] "GET /pnews/浙江省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:28] "GET /prank/湖北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:28] "GET /pmap/浙江省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:05:29] "GET /prank/浙江省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:11] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:16] "GET /news HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:16] "GET /overall HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:17] "GET /poverall/安徽省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:17] "GET /pnews/安徽省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:17] "GET /map HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:18] "GET /rank HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:20] "GET /pmap/安徽省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:20] "GET /prank/安徽省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:20] "GET /poverall/河北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:20] "GET /pnews/河北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:20] "GET /pmap/河北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:22] "GET /prank/河北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:23] "GET /pnews/湖北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:23] "GET /poverall/湖北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:23] "GET /prank/湖北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:24] "GET /pmap/湖北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:24] "GET /poverall/浙江省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:24] "GET /pnews/浙江省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:24] "GET /pmap/浙江省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:24] "GET /prank/浙江省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:25] "GET /news HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:25] "GET /overall HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:25] "GET /poverall/安徽省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:25] "GET /pnews/安徽省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:26] "GET /map HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:26] "GET /pmap/安徽省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:26] "GET /prank/安徽省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:26] "GET /rank HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:26] "GET /poverall/河北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:27] "GET /pmap/河北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:27] "GET /prank/河北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:27] "GET /poverall/湖北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:27] "GET /pnews/湖北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:27] "GET /pnews/河北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:27] "GET /prank/湖北省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:28] "GET /poverall/浙江省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:28] "GET /pnews/浙江省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:28] "GET /pmap/浙江省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:28] "GET /prank/浙江省 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:06:28] "GET /pmap/湖北省 HTTP/1.1" 200 -

**Comment by hack-fang** [comment]
> 
> 
> 代码是最新的.地图包也导入了.
> 
> ```
>     update_china("china");
>     update_province("浙江省","zhejiang");
>     update_province("广东省","guangdong");
> 
> <script type="text/javascript" src="/static/vendor/map/zhejiang.js"></script>
> <script type="text/javascript" src="/static/vendor/map/guangdong.js"></script>
> ```
> 
> 看了下日志,就是广东的数据没有取过来,不知道为啥?
> 127.0.0.1 - - [30/Jan/2020 19:05:05] "GET / HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:07] "GET /poverall/安徽省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:07] "GET /rank HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:07] "GET /news HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:08] "GET /overall HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:08] "GET /pnews/安徽省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:09] "GET /map HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:09] "GET /pmap/安徽省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:09] "GET /prank/安徽省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:09] "GET /poverall/河北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:09] "GET /pnews/河北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:09] "GET /pmap/河北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:10] "GET /prank/河北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:20] "GET /poverall/湖北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:20] "GET /pnews/湖北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:20] "GET /pmap/湖北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:20] "GET /poverall/浙江省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:20] "GET /pnews/浙江省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:21] "GET /prank/湖北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:23] "GET /pmap/浙江省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:23] "GET /prank/浙江省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:24] "GET /poverall/安徽省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:25] "GET /rank HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:25] "GET /news HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:25] "GET /overall HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:25] "GET /pnews/安徽省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:26] "GET /pmap/安徽省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:26] "GET /map HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:26] "GET /prank/安徽省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:26] "GET /poverall/河北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:27] "GET /pnews/河北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:28] "GET /pmap/河北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:28] "GET /prank/河北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:28] "GET /poverall/湖北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:28] "GET /pnews/湖北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:28] "GET /pmap/湖北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:28] "GET /poverall/浙江省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:28] "GET /pnews/浙江省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:28] "GET /prank/湖北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:28] "GET /pmap/浙江省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:05:29] "GET /prank/浙江省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:11] "GET / HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:16] "GET /news HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:16] "GET /overall HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:17] "GET /poverall/安徽省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:17] "GET /pnews/安徽省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:17] "GET /map HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:18] "GET /rank HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:20] "GET /pmap/安徽省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:20] "GET /prank/安徽省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:20] "GET /poverall/河北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:20] "GET /pnews/河北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:20] "GET /pmap/河北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:22] "GET /prank/河北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:23] "GET /pnews/湖北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:23] "GET /poverall/湖北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:23] "GET /prank/湖北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:24] "GET /pmap/湖北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:24] "GET /poverall/浙江省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:24] "GET /pnews/浙江省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:24] "GET /pmap/浙江省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:24] "GET /prank/浙江省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:25] "GET /news HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:25] "GET /overall HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:25] "GET /poverall/安徽省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:25] "GET /pnews/安徽省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:26] "GET /map HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:26] "GET /pmap/安徽省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:26] "GET /prank/安徽省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:26] "GET /rank HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:26] "GET /poverall/河北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:27] "GET /pmap/河北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:27] "GET /prank/河北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:27] "GET /poverall/湖北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:27] "GET /pnews/湖北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:27] "GET /pnews/河北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:27] "GET /prank/湖北省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:28] "GET /poverall/浙江省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:28] "GET /pnews/浙江省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:28] "GET /pmap/浙江省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:28] "GET /prank/浙江省 HTTP/1.1" 200 -
> 127.0.0.1 - - [30/Jan/2020 19:06:28] "GET /pmap/湖北省 HTTP/1.1" 200 -

可能是第三方接口速度过慢的原因(测了下请求一次费时20s)导致的，我增加了一个guangdong分支，你可以对比下代码测试下。后续考虑开放自己的接口以提高请求响应速度。
https://github.com/hack-fang/nCov/tree/guangdong

**Comment by quuhua911** [comment]
大概是接口问题，我下载了guangdong分支，还是取不到广东数据．python app.py
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 252-753-646
127.0.0.1 - - [30/Jan/2020 19:53:14] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:53:22] "GET /overall HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:53:22] "GET /rank HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:53:23] "GET /news HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:53:24] "GET /map HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:53:29] "GET /overall HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:53:30] "GET /rank HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:53:31] "GET /news HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 19:53:32] "GET /map HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 20:58:12] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 20:58:13] "GET /news HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 20:58:14] "GET /map HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 20:58:15] "GET /overall HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 20:58:15] "GET /rank HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 20:58:16] "GET /news HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 20:58:18] "GET /map HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 20:58:19] "GET /overall HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2020 20:58:19] "GET /rank HTTP/1.1" 200 -

**Comment by hack-fang** [comment]
> 
> 
> 大概是接口问题，我下载了guangdong分支，还是取不到广东数据．python app.py
> 
>     * Serving Flask app "app" (lazy loading)
> 
>     * Environment: production
>       WARNING: This is a development server. Do not use it in a production deployment.
>       Use a production WSGI server instead.
> 
>     * Debug mode: on
> 
>     * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
> 
>     * Restarting with stat
> 
>     * Debugger is active!
> 
>     * Debugger PIN: 252-753-646
>       127.0.0.1 - - [30/Jan/2020 19:53:14] "GET / HTTP/1.1" 200 -
>       127.0.0.1 - - [30/Jan/2020 19:53:22] "GET /overall HTTP/1.1" 200 -
>       127.0.0.1 - - [30/Jan/2020 19:53:22] "GET /rank HTTP/1.1" 200 -
>       127.0.0.1 - - [30/Jan/2020 19:53:23] "GET /news HTTP/1.1" 200 -
>       127.0.0.1 - - [30/Jan/2020 19:53:24] "GET /map HTTP/1.1" 200 -
>       127.0.0.1 - - [30/Jan/2020 19:53:29] "GET /overall HTTP/1.1" 200 -
>       127.0.0.1 - - [30/Jan/2020 19:53:30] "GET /rank HTTP/1.1" 200 -
>       127.0.0.1 - - [30/Jan/2020 19:53:31] "GET /news HTTP/1.1" 200 -
>       127.0.0.1 - - [30/Jan/2020 19:53:32] "GET /map HTTP/1.1" 200 -
>       127.0.0.1 - - [30/Jan/2020 20:58:12] "GET / HTTP/1.1" 200 -
>       127.0.0.1 - - [30/Jan/2020 20:58:13] "GET /news HTTP/1.1" 200 -
>       127.0.0.1 - - [30/Jan/2020 20:58:14] "GET /map HTTP/1.1" 200 -
>       127.0.0.1 - - [30/Jan/2020 20:58:15] "GET /overall HTTP/1.1" 200 -
>       127.0.0.1 - - [30/Jan/2020 20:58:15] "GET /rank HTTP/1.1" 200 -
>       127.0.0.1 - - [30/Jan/2020 20:58:16] "GET /news HTTP/1.1" 200 -
>       127.0.0.1 - - [30/Jan/2020 20:58:18] "GET /map HTTP/1.1" 200 -
>       127.0.0.1 - - [30/Jan/2020 20:58:19] "GET /overall HTTP/1.1" 200 -
>       127.0.0.1 - - [30/Jan/2020 20:58:19] "GET /rank HTTP/1.1" 200 -

1. 最新版本程序已使用 自开发的API接口，完全兼容第三方的API，访问速度更快。
2.  或用 https://lab.ahusmart.com/nCoV/api/ 替换第三方API网址即可
