### ISSUE TITLE
部分县市地图不更新数据

### ISSUE THREAD

**Issue by WeileiZeng** [hack-fang/nCov#3]
https://yiqing.ahusmart.com/

比如湖北恩施，在地图上没有显示

猜测原因是地图数据用了不同的城市名，需要手动修改使其同步

**Comment by hack-fang** [comment]
是的，echarts 地图需要传入完整的城市名。而接口提供的城市名有的市简写，所以地图上不显示。

最新版本已手动整理增加了目前最新的对照表，https://github.com/hack-fang/nCov/blob/master/province_cities.json 暂时解决了部分城市地图不显示的bug。
