### ISSUE TITLE
为其他省份添加一个单独页面？

### ISSUE THREAD

**Issue by WeileiZeng** [hack-fang/nCov#4]
给每个省份添加一个单独页面？ 这样其他人不用去部署域名和网页等等。

我觉得这个需求还是蛮需要的。

**Comment by hack-fang** [comment]
抱歉，由于我的前端能力是业余的水平，网页设计不好，短期内不会去实现。如果有兴趣的话可以fork后实现。

目前工作重心是开发 **基于server酱 微信实时推送自定义疫情信息** 的项目

**Comment by WeileiZeng** [comment]
我试了一下，本地可以运行，但是菜鸟不会deploy。。

**Comment by hack-fang** [comment]
> 
> 
> 我试了一下，本地可以运行，但是菜鸟不会deploy。。



> 
> 
> 我试了一下，本地可以运行，但是菜鸟不会deploy。。

如果用户量不大，docker部署是最简单的，git clone 项目到服务器上，执行docker build  和docker run 命令即可，打开相应的ip:port即可。或者服务器直接装好python环境，后台运行即可。


如果用户量较大，请参考 http://docs.jinkan.org/docs/flask/deploying/index.html

个人建议直接运行或docker运行
