### ISSUE TITLE
读取西藏自治区和台湾省的报错了

### ISSUE THREAD

**Issue by deepwindlee** [hack-fang/nCov#5]
# 获取某省份各市数据数据
def update_province_data(province):
    baseUrl = "https://lab.ahusmart.com/nCoV/api/"
    url = baseUrl +'area?latest=1&province='+province
    province_data = json.loads(requests.get(url).text)
    province_data['time'] = time.strftime(
        "%m-%d %H:%M", time.localtime(time.time()))

    # 取最新一条统计数据
    latest_data = province_data["results"][0]
    cities_data = []
    for  c  in latest_data["cities"]:
        city_data = []
        city_data.append(province)
        
        # 先在修正表中找
        '''
        if province_city_fixed[province][c["cityName"]]!=None:
            city_data.append(province_city_fixed[province][c["cityName"]])
        # 没有则延用原始名称
        else:
            city_data.append(c["cityName"])'
        '''
        try:
            city_data.append(province_city_fixed[province][c["cityName"]])
        except:
            city_data.append(c["cityName"])
        else:
            pass
            
            

        city_data.append(c["confirmedCount"])
        cities_data.append(city_data)

    return cities_data

**Comment by hack-fang** [comment]
感谢

> 
> # 获取某省份各市数据数据
> 
> def update_province_data(province):
> baseUrl = "https://lab.ahusmart.com/nCoV/api/"
> url = baseUrl +'area?latest=1&province='+province
> province_data = json.loads(requests.get(url).text)
> province_data['time'] = time.strftime(
> "%m-%d %H:%M", time.localtime(time.time()))
> 
> ```
> # 取最新一条统计数据
> latest_data = province_data["results"][0]
> cities_data = []
> for  c  in latest_data["cities"]:
>     city_data = []
>     city_data.append(province)
>     
>     # 先在修正表中找
>     '''
>     if province_city_fixed[province][c["cityName"]]!=None:
>         city_data.append(province_city_fixed[province][c["cityName"]])
>     # 没有则延用原始名称
>     else:
>         city_data.append(c["cityName"])'
>     '''
>     try:
>         city_data.append(province_city_fixed[province][c["cityName"]])
>     except:
>         city_data.append(c["cityName"])
>     else:
>         pass
>         
>         
> 
>     city_data.append(c["confirmedCount"])
>     cities_data.append(city_data)
> 
> return cities_data
> ```

感谢反馈，已修复，西藏和台湾没有公布城市的数据，请参考[丁香园](https://ncov.dxy.cn/ncovh5/view/pneumonia) 公布的数据
