### ISSUE TITLE
疫情数据的获取

### ISSUE THREAD

**Issue by BarryBA** [hack-fang/nCov#7]
请问，所用的疫情数据是从丁香网页上爬取的吗？
有没有具体到省级甚至县市级的疫情数据公开源呢？

**Comment by hack-fang** [comment]
> 
> 
> 请问，所用的疫情数据是从丁香网页上爬取的吗？
> 有没有具体到省级甚至县市级的疫情数据公开源呢？

是爬取自丁香网页的，省级到市级数据是有的，你通过接口文档 https://github.com/hack-fang/nCov/blob/master/API.md

**Comment by BarryBA** [comment]
> > 请问，所用的疫情数据是从丁香网页上爬取的吗？
> > 有没有具体到省级甚至县市级的疫情数据公开源呢？
> 
> 是爬取自丁香网页的，省级到市级数据是有的，你通过接口文档 https://github.com/hack-fang/nCov/blob/master/API.md

感谢
是否有公开的病例数据文档呢？
我关注到有些公开数据中仅有确诊、治愈、死亡数据，并未统计疑似病例的每天数据

**Comment by hack-fang** [comment]
> 
> 
> > > 请问，所用的疫情数据是从丁香网页上爬取的吗？
> > > 有没有具体到省级甚至县市级的疫情数据公开源呢？
> > 
> > 
> > 是爬取自丁香网页的，省级到市级数据是有的，你通过接口文档 https://github.com/hack-fang/nCov/blob/master/API.md
> 
> 感谢
> 是否有公开的病例数据文档呢？
> 我关注到有些公开数据中仅有确诊、治愈、死亡数据，并未统计疑似病例的每天数据

丁香园没有发布疑似病例相应的数据，因此接口没有相应的数据。
